### ISSUE TITLE
license - lgpl instead of gpl ?

### ISSUE THREAD

**Issue by mooreatv** [SafeteeWoW/LibDeflate#4]
Hi there,

Can you relicense this great work under LPGLv3 so it can actually be used by Wow and Wow addons ? (unless somehow I misinterpret the GPL but it seems pretty clear I am afraid?)

Thanks!

**Comment by SafeteeWoW** [comment]
Though I do not think GPL will affect WoW addon to use LibDeflate, I can change the license to LGPLv3, to make it used by more people

The main reason that LibDeflate was licensed under GPLv3, because LibCompress (https://www.wowace.com/projects/libcompress) is also GPLv2, and I do not think this affects the WoW addon development. 

The official WoW addon policy (https://us.forums.blizzard.com/en/wow/t/ui-add-on-development-policy/24534) requires 

> Add-on code must be completely visible.
> The programming code of an add-on must in no way be hidden or obfuscated, and must be freely accessible to and viewable by the general public.

This means that the Lua code running inside World of Warcraft must be open source, although you could obfuscate the source code to make it hard to read. You could make it close-source for helper programs not written in Lua that running outside World of Warcraft, similar a database auto updater, which is not affected by GPLv3 even if you use any Lua GPL library. In a word, WoW addon policy requires addon Lua code to be "GPL" anyway, so GPL is not a problem for you to use GPL library.

I did use some GPL code in the testing part though, I will license testing code in GPL, but LibDeflate.lua itself in LGPLv3

P.S.: I am not playing WoW for more than a year, sorry for very late reply. Trying to remember how to how to do lua packaging and Wow packaging stuffs.

**Comment by SafeteeWoW** [comment]
Will update the license and the version number in several days after setting up my Lua development environment and after downloading a WoW client for further testing

**Comment by SafeteeWoW** [comment]
@mooreatv  @Stanzilla   Version 1.0.1 has been released. I have replaced every mentions of GPL of LibDeflate to LGPL, including the source code, README, documentation, Luarocks page, Curseforge page. Report if there is still any GPL leftovers.
